### ISSUE TITLE
Authentication failed: Password not allowed for insecure authentication

### ISSUE THREAD

**Issue by gitdep** [starburstdata/metabase-driver#101]
When connecting from Metabase v0.46.5 using the Starburst driver v3.0.1 to Trino 419, I encounter the error "Authentication failed: Password not allowed for insecure authentication."
Has anyone encountered this situation and can provide assistance? Thank you.

**Comment by lpoulain** [comment]
This is not a Metabase connector issue but an underlying Trino feature: password authentication is not allowed when trying to connect to Trino using HTTP instead of HTTPS. The fix is to either switch to HTTPS or just configure Trino to accept username authentication (without password). See `https://www.trinoforum.org/t/why-does-trino-require-https-for-user-pass-the-answer-may-surprise-you/81`
