### ISSUE TITLE
Trying to cast timestamp when report timezone is set

### ISSUE THREAD

**Issue by kempspo** [starburstdata/metabase-driver#58]
Timestamp are showing up always as set report timezone even when casted using `at time zone`. 

Metabase report timezone is set to US/Pacific, results are correct for US/Pacific. However, does not show up correctly when I want to cast it back to UTC or any other time zone. The same thing if `at_timezone` function is used

Expected behavior: 
`_col1` and `_col2` to show up as '2012-10-31 01:00 UTC' and '2022-01-01 00:00:00 UTC' respectively

![Screen Shot 2022-11-22 at 11 22 54 PM](https://user-images.githubusercontent.com/32265362/203352622-6ebe9171-f49d-4813-8270-75ced38383ce.png)

**Comment by kempspo** [comment]
For comparison, this is how the postgres connector would behave
![Screen Shot 2022-11-22 at 11 30 27 PM](https://user-images.githubusercontent.com/32265362/203354584-d7f68ed0-85cc-4f96-8b9f-6c448dad8ab4.png)

**Comment by leniartek** [comment]
Hi @kempspo, thats for reporting this.

Please provide some more details about your environment:
- version of Starburst/Trino
- version of Metabase
- version of Starburst Metabase driver?

**Comment by kempspo** [comment]
- Trino Version: 401
- Metabase Version: 1.44.5
- Starburst Metabase Driver Version: 1.0.6

Please let me know if you need any other details

**Comment by xsgao-github** [comment]
This seems to be a Metabase issue to me.

Datasource provides `data` (in 0/1 format) and BI tool presents them `visually`. Trino is able to transfer data correctly to Metabase but Metabase decides to show them all in the reporting timezone. You can cast the data at the data source level to force them to show in different timezones (usually is against best BI best practice though).

The following screenshot shows that DBeaver wants to show dt with timezone at client timezone, as Metabase does:

<img width="1423" alt="Screenshot 2022-11-23 at 10 50 08 AM" src="https://user-images.githubusercontent.com/39278329/203590235-61a7b6d0-563f-4edc-81a1-035ced4a68a9.png">

And the following screenshot shows that the ODBCTest tool simply displays the string representation as you were expecting:

<img width="874" alt="Screenshot 2022-11-23 at 10 52 31 AM" src="https://user-images.githubusercontent.com/39278329/203590864-953995af-4cbc-48d9-9549-6a1b971de9ba.png">

**Comment by kempspo** [comment]
@xsgao-github what you're saying makes sense, what leads me to believe it's a driver issue is because testing the same query on say a postgresql on the same metabase instance, the time zone casting works.

**Comment by andrewdibiasio6** [comment]
Issue is likely caused by this line: https://github.com/starburstdata/metabase-driver/blob/main/drivers/starburst/src/metabase/driver/implementation/execute.clj#L126

And we should also fix:

https://github.com/starburstdata/metabase-driver/blob/main/drivers/starburst/src/metabase/driver/implementation/execute.clj#L134-L138

We should try to convert following approach:
java.time.ZonedDateTime

**Comment by lpoulain** [comment]
After some further review, it turns out that the behavior seen is the correct one. Indeed, if we consider the first two columns:

- Starburst returns the exact same timestamp albeit with two different timezones (2010-10-30T18:00-07:00[America/Los_Angeles] and 2010-10-31T01:00Z[UTC]), which is the expected behavior
- The time zone is then converted by Metabase to the local time
 
So it makes sense that the first two columns return the same value. This was confirmed by Metabase (https://discourse.metabase.com/t/handling-of-timestamps-with-time-zone/23004)

Why is PostgreSQL showing a different result? It turns out that PostgreSQL "WITH TIME ZONE" behaves differently than Starburst's and actually modifies the timestamp. TIMESTAMP '2010-10-31 01:00 UTC' AT TIME ZONE 'America/Los_Angeles' returns 2010-10-31 08:00:00+00 whereas TIMESTAMP '2010-10-31 01:00 UTC' AT TIME ZONE 'UTC' returns 2010-10-31 01:00:00+00.

**Comment by xsgao-github** [comment]
> TIMESTAMP '2010-10-31 01:00 UTC' AT TIME ZONE 'America/Los_Angeles' returns 2010-10-31 08:00:00+00

@lpoulain You cannot use `at time zone` function to `timestamp (without timezone)`, which caused a weird value here. **`TIMESTAMPTZ`**` '2010-10-31 01:00 UTC' AT TIME ZONE 'America/Los_Angeles' ` gives correct values.

But I agree to cast all timestamp values to a single timezone is the correct choice. Otherwise, as Postgres driver does, it will bring more confusion - users have to link values back to their corresponding/various timezones, and joining data by timestamp in two different timezones will be very difficult.

**Comment by aalbu** [comment]
To summarize here, the difference in behavior between PostgreSQL and Trino is due to the fact that although the queries in the examples look very similar, they return different data types.

`SELECT timestamptz '2012-10-31 01:00 UTC' AT TIME ZONE 'US/Pacific'`
In PostgreSQL, this returns a `timestamp without time zone`, in other words, a local timestamp that has no associated time zone information.  So `AT TIME ZONE` turns a `timestamp with time zone` into a `timestamp without time zone` (see https://www.postgresql.org/docs/11/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT - thank you to @mdesmet for providing the explanation).

`SELECT timestamp '2012-10-31 01:00 UTC' AT TIME ZONE 'US/Pacific'`
In Trino, this returns a `timestamp(0) with time zone`, so it's the original point in time with a different time zone.  Metabase displays this in the UTC time zone.
